[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]


[dependencies]
num = "^0.4.1"
crossbeam = "^0.8.3"
rayon = "^1.8.0"
serde = { version = "1.0", features = ["derive"] }
